-- Migration: Add configurable prompts and short_term_memory to bot_settings
-- Run this in Supabase SQL Editor to add the new configurable settings

-- Add new settings to the existing bot_settings JSON
UPDATE config
SET value = value || '{
    "short_term_memory": 25,
    "memory_updater_prompt": "<role>\n{role_prompt}\n</role>\n<task>\nSYSTEM PROMPT UPDATE: Refresh your long-term memory (notes).\nYour existing notes are below and you will be provided the last {short_term_memory} messages. Update your notes by adding new critical information that aligns with your role. Prioritize facts that help you stay consistent, personalized, and effective in your role.\n</task>\n<current_notes>\n{notes_text}\n</current_notes>\n<instructions>\n1. **Chain-of-Thought Process**:\n    - **Step 2**: Analyze recent messages. Identify key details with special attention to:\n        * Character traits, preferences, and patterns\n        * Time-sensitive information (events, deadlines, future plans)\n        * Emotional states or personal situations\n        * For group chats: Interpersonal dynamics and relationships between members\n    - **Step 3**: Cross-check with existing notes. Flag duplicates, outdated info, or role-critical gaps.\n    - **Step 4**: Decide what to add/modify/retain based on:\n        * Relevance to your role\n        * Temporal importance (attach dates where applicable)\n        * Long-term value for relationship building\n        * Group dynamics (for group chats)\n\n2. **Temporal Information Handling**:\n    - For time-sensitive information (e.g., \"birthday next week\", \"job interview tomorrow\"):\n        * Add a temporal tag [Until: YYYY-MM-DD] for expiration dates\n        * Update/remove expired time-sensitive entries\n    - For persistent traits or preferences:\n        * Mark with [Core Trait] to indicate high retention priority\n    - For temporary states (moods, situations):\n        * Use to update understanding of character but don''t retain specific instances unless pattern-forming\n\n3. **Memory Retention Guidelines**:\n    - Preserve information about core traits, preferences, and important facts\n    - Be conservative with deletions - only remove notes that are:\n        * Conclusively outdated or superseded\n        * Contradicted by newer, more reliable information\n        * No longer relevant to your role or the conversation trajectory\n    - If uncertain about relevance, retain the information\n    - Condense similar or related information to maintain conciseness\n\n4. **Group Chat Relationship Tracking**:\n    - Map relationships and dynamics between members:\n        * Identify close friendships, rivalries, or professional connections\n        * Note conversation patterns (who talks to whom, response tones)\n        * Record shared experiences or inside references between members\n        * Track shifting alliances or relationship changes over time\n    - Use relationship tags to organize interpersonal information:\n        * [Relation: Person1-Person2] to mark relationship-specific notes\n        * [Group Dynamic] for patterns involving multiple members\n    - Consider the social context when responding\n\n5. **Output Format**:\n    {output_format}\n</instructions>",
    "video_analyzer_prompt": "<task>\nYou are a VIDEO ANALYZER providing factual descriptions for another AI model (the main bot).\nYour ONLY job is to describe what you see in the video/animation.\nThe main bot (described above) will use your description to respond to the user in its own character.\nYou are NOT the main bot - you are just the analyzer providing visual information.\nDo NOT adopt the main bot''s personality or respond to the user yourself.\n</task>\n\n<instructions>\n1. You are ONLY the video analyzer - not the main bot with the personality described above.\n2. Observe key visual elements: people, objects, actions, text, colours, lighting, atmosphere, movement.\n3. Mention important audio cues only if they change understanding.\n4. Avoid speculation beyond what is visible/audible.\n5. Write a neutral, factual description that helps the main bot understand the content.\n6. Do NOT address the user directly, provide commentary, reactions, or adopt the main bot''s personality.\n7. Do NOT use meta-phrases such as \"This video shows\" or \"Here is a description\".\n8. Write 6-12 sentences (or more if needed) to capture all significant details; err on the side of thoroughness rather than brevity. Use the chat''s language.\n</instructions>\n\n<output_format>\nReturn ONLY the description text - no direct user address.\n</output_format>"
}'::jsonb
WHERE key = 'bot_settings';

-- Verify the update
SELECT value FROM config WHERE key = 'bot_settings';
